### PR TITLE
travis: don't test the master branch

### PR DESCRIPTION
**Pull request by japaric**
everything will go through homu

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit beb49af has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit beb49af with merge beb49af...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/eighty-six/builds/148578809)

**Pull request merged**
