### PR TITLE
ci: test mk-iso.sh

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit dda1e59 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit dda1e59 with merge dda1e59...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/eighty-six/builds/148579476)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 23842f4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 23842f4 with merge 23842f4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/eighty-six/builds/148579838)

**Pull request merged**
